# Generated by Django 5.1.1 on 2024-12-28 16:22

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the blog post.', max_length=200)),
                ('content', tinymce.models.HTMLField(help_text='Write the content of the blog post here.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this post was created.')),
            ],
        ),
    ]
